name: '💥🚀 Amazing Feature Request 💥🚀'
description: "Suggest an idea for making our app even more awesome! 🔥🙌"
labels: ['type:enhancement']
assignees: ''

sections:
  - title: "🤔 Is your proposal related to a problem?"
    questions:
      - id: 'problem-description'
        title: "💥 What's the problem?"
        type: 'textarea'
        placeholder: "I'm always frustrated when..."
        required: true

  - title: "💡 Describe the solution you'd like"
    questions:
      - id: 'solution-description'
        title: "💡 What's your idea?"
        type: 'textarea'
        placeholder: "I'd love it if the app could..."
        required: true

  - title: "💡 Alternatives you've considered"
    questions:
      - id: 'alternatives-description'
        title: "🤔 Have you thought of other solutions?"
        type: 'textarea'
        placeholder: "I've also considered..."
        required: false

  - title: "🌟 Additional context"
    questions:
      - id: 'additional-context'
        title: "🌟 Anything else you'd like to add?"
        type: 'textarea'
        placeholder: "This feature would be especially useful for..."
        required: false

  - title: "📌 Code of Conduct"
    questions:
      - id: 'code-of-conduct'
        title: "📌 Code of Conduct"
        type: 'checkbox'
        description: "By submitting this issue, you agree to follow our Code of Conduct."
        options:
          - value: 'agree'
            label: "I agree to follow the Code of Conduct"
            required: true
